### ISSUE TITLE
Declarations for HTMLHelpShowContents and HTMLHelpShowSearch for VBA7

### ISSUE THREAD

**Issue by DirkFromme** [GustavBrock/VBA.HtmlHelp#1]
First: great work, thanks.

Just to improve: Shouldn't they return LongPtr instead of Long?:

#If VBA7 Then
    Private Declare PtrSafe Function HTMLHelpShowContents Lib "hhctrl.ocx" Alias "HtmlHelpA" ( _
        ByVal hwnd As LongPtr, _
        ByVal lpHelpFile As String, _
        ByVal wCommand As Long, _
        ByVal dwData As Long) _
        As LongPtr
#Else
    Private Declare Function HTMLHelpShowContents Lib "hhctrl.ocx" Alias "HtmlHelpA" ( _
        ByVal hwnd As Long, _
        ByVal lpHelpFile As String, _
        ByVal wCommand As Long, _
        ByVal dwData As Long) _
        As Long
#End If

' Open a compiled HTML help file (.chm) with the Search tab active.
#If VBA7 Then
    Private Declare PtrSafe Function HTMLHelpShowSearch Lib "hhctrl.ocx" Alias "HtmlHelpA" ( _
        ByVal hwnd As LongPtr, _
        ByVal lpHelpFile As String, _
        ByVal wCommand As Long, _
        ByRef dwData As HhFtsQuery) _
        As LongPtr
#Else
    Private Declare Function HTMLHelpShowSearch Lib "hhctrl.ocx" Alias "HtmlHelpA" ( _
        ByVal hwnd As Long, _
        ByVal lpHelpFile As String, _
        ByVal wCommand As Long, _
        ByRef dwData As HhFtsQuery) _
        As Long
#End If

**Comment by GustavBrock** [comment]
Not to my knowledge, as the call returns a _window handle_:
[HtmlHelpA function (htmlhelp.h)](https://learn.microsoft.com/en-us/windows/win32/api/htmlhelp/nf-htmlhelp-htmlhelpa?WT.mc_id=M365-MVP-5002361#return-value)
and that should be a Long.
